### PR TITLE
Traducción Capítulo 14 Pythonlearn-14-Objetos.pptx

### PR DESCRIPTION
**Pull request by miltonlab**
[Pythonlearn-14-Objetos.pptx](https://github.com/csev/py4e/files/4778507/Pythonlearn-14-Objetos.pptx)
 Traducción al español del Capítulo 14 Objetos.

### CODE REVIEW

**Comment by miltonlab** [comment]
Hi friends, i would like to know if my request will be reviewed ?

**Comment by csev** [comment]
This pull request has a lot of merge conflicts.  I can't read Spanish and have no idea about these merges.   The subfolders like book3/convert/ and book3/html/ should not be modified - some are historic and others are auto-generated from the mkd files.

I have no idea what this was trying to accomplish.

**Comment by miltonlab** [comment]
I want only upload the Pythonlearn-14-Objetos.pptx to contribute !!!

**Comment by csev** [comment]
You are sending this PR to the English repo - it needs to be sent to the Spanish repo.

**Pull request closed without merging**
