### PR TITLE
First set of spanish translations

### PR DESCRIPTION
**Pull request by Markjcp**

### CODE REVIEW

**Comment by Markjcp** [comment]
Sorry @konkiourtidou do you know if there is someone that can review this one? I am trying to reach Charles from late january and I couldn't

**Comment by konkiourtidou** [comment]
@Markjcp I'm afraid that the only one who can review this is Dr. Chuck
At the time, I think, he has a very busy schedule. When he finds the time he will check it. 
Keep translating and he will check them all

**Comment by Markjcp** [comment]
> @Markjcp I'm afraid that the only one who can review this is Dr. Chuck At the time, I think, he has a very busy schedule. When he finds the time he will check it. Keep translating and he will check them all

Awesome, we'll continue then

**Comment by konkiourtidou** [comment]
> > @Markjcp I'm afraid that the only one who can review this is Dr. Chuck At the time, I think, he has a very busy schedule. When he finds the time he will check it. Keep translating and he will check them all
> 
> Awesome, we'll continue then

@Markjcp I've just remembered something dr. Chuck mentioned on his last live (https://m.youtube.com/watch?v=XpeYyoxamp4&t=7141s), if I'm not mistaken, he said something about changing some topics of py4e...
Perhaps you should try again to contact him before proceeding

**Comment by csev** [comment]
Hello @Markjcp - I am so sorry to have been so useless on this topic the past few months.  The good news is that YouTube now (this week) has made it so you can manage the translations if you have a YouTube account - I can give you permissions to directly edit the captions - that way you can do any of my courses and fix little things easily if you find them later.  Send me email with your YouTube account...

**Comment by csev** [comment]
Sorry for the delay - I am now on this.

**Comment by Markjcp** [comment]
Now I am really sorry. I completely forgot about this but I want to take it
again this quarter.
My youtube account I think is this same mail. Isn't irñt?

**Pull request merged**
