### PR TITLE
Rephrasing in ch.15

### PR DESCRIPTION
**Pull request by konkiourtidou**
I think this is a little clearer

### CODE REVIEW

**Review by csev — COMMENTED** [review]
Just a wording change to the wording change :)

**Comment by csev** [comment]
"does no exist" should be "does not exist"

**Comment by konkiourtidou** [comment]
on line 540 did I get it right?

**Comment by csev** [comment]
I did not check line 540 - I just assumed you knew what you were doing.

**Comment by konkiourtidou** [comment]
:)) I think so...

2022-08-24 23:07 GMT+03:00, Charles Severance ***@***.***>:

**Pull request merged**
