### PR TITLE
typos and a clarification

### PR DESCRIPTION
**Pull request by konkiourtidou**
also, in lines 537 to 540 I think, there is a kind of self-reference, explaining the object with the term instance, while you mention below that the two terms are used in the literature interchangeably

### CODE REVIEW

**Comment by csev** [comment]
I agree.

**Comment by konkiourtidou** [comment]
perhaps something like:
"object is an entity created by the class with specific properties"

I can't find the right word to translate it from greek ... :(

Στις Τετ 24 Αυγ 2022 στις 11:02 μ.μ., ο/η Charles Severance <
***@***.***> έγραψε:

**Comment by csev** [comment]
I think it is OK the way that it is.
`:   A constructed instance of a class.  An object contains all of
    the attributes and methods that were defined by the class.
    Some object-oriented documentation uses the term 'instance'
    interchangeably with 'object'.
`
Yes, it is a bit recursive. The last sentence is not the essence of the definition.  You could debate that it is less confusing without the last sentence.  But the last sentence adds some value.  In a sense, the 'instance' in the first sentance is just the word as defined in English - in the last sentence "instance" is in effect a technically defined word in other documentation.

**Comment by csev** [comment]
You can adjust it in Greek - but I like it the way it is in English.  Even if it is a little self-referential.

**Pull request merged**
